# https://www.getambassador.io/docs/emissary/latest/topics/running/services/auth-service
apiVersion: getambassador.io/v3alpha1
kind: AuthService
metadata:
  name: standalone-auth
spec:
  auth_service: "standalone-auth.default:3000"
  proto: http
  
  # How to handle authn/authz failure
  failure_mode_allow: false
  timeout_ms: 1000
  status_on_error:
    code: 403

  # Headers expected to contain authentication credentials
  allowed_request_headers:
  - "X-Mycompany-Api-Key"
  # - "X-Mycompany-User-Id"
  # - "X-Mycompany-User-Name"
  
  # Headers that we expect/allow to be added by standalone-auth after authn/authz
  allowed_authorization_headers:
  # - "X-Mycompany-Api-Key"
  - "X-Mycompany-User-Id"
  - "X-Mycompany-User-Name"
  - "X-Mycompany-Path"

  allowed_headers:
  - "X-Mycompany-User-Id"
  - "X-Mycompany-User-Name"
  - "X-Mycompany-Path"
